services:
  dev_loveShopAPI:
    image: love_shop_api
    container_name: dev_love_shop_api_container
    build:
      context: .
      dockerfile: LoveShop/Dockerfile
    ports:
      - ${API_PORT}:8080
    depends_on:
      - dev_postgres
    environment:
      - 'ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}'
      - 'ConnectionStrings:Database=Host=dev_postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}'
    networks:
      - dev_postgres

  dev_postgres:
    image: postgres:16-alpine
    container_name: dev_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/dev_pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /Dev_Init_Database:/dev_docker-entrypoint-initdb.d
      - dev_pg-data:/var/lib/postgresql/dev_data
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    command: >
      postgres -c max_connections=50
               -c shared_buffers=1GB
               -c effective_cache_size=2GB
               -c work_mem=16MB
               -c maintenance_work_mem=512MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - dev_postgres

  dev_pgadmin:
    container_name: dev_pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - dev_pgadmin-data:/var/lib/dev_pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - dev_postgres

volumes:
  dev_pg-data:
  dev_pgadmin-data:


networks:
  dev_postgres:
    driver: bridge
